### ISSUE TITLE
确实挺好用，但如果从后台获取uptoken，没看到怎么配置呢，我重写的

### ISSUE THREAD

**Issue by liumingsongning** [cag2050/qiniu_demo#2]

**Comment by cag2050** [comment]
从后台获取uptoken，一般是后端提供接口，前端从接口取uptoken

**Comment by liumingsongning** [comment]
你项目可以稍微 改下，让用户自己直接配路由就可以了，要不然自己弄要改你组件才行，感觉那不大好

**Comment by cag2050** [comment]
@liumingsongning  用的话，复制一下代码，稍微改造下就可以。这个是在vue项目里做的。
